services:
  # Service MongoDB
  mongo:
    image: mongo
    container_name: vibehub-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Service Backend
  backend:
    build: ./vibehub-backend
    container_name: vibehub-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/vibehub
    volumes:
      - ./vibehub-backend:/app
      - /app/node_modules

  # Service Flask API (Détection d’émotions et modération)
  backend-ia:
    build: ./vibehub-ia
    container_name: vibehub-ia
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./vibehub-ia:/app

  # Service Frontend
  frontend:
    build: ./vibehub-frontend
    container_name: vibehub-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_FLASK_API_URL=http://localhost:5001  # Ajout de l’URL de l’API Flask
    volumes:
      - ./vibehub-frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
